const calcSave = (base, each, number) => {
  const savedETH = (base - each) * number;
  const percSaved = ((base - each) / base) * 100;

  const str = `${Number(percSaved).toFixed(0)}% / ${Number(savedETH).toFixed(
    3
  )}`;
  return str;
};

const allCurrencyRoundInfoArray = [
  [
    [], //never used
    [
      {
        each: 0.05,
        total: 0.05 * 1,
        number: 1,
        save: calcSave(0.05, 0.05, 1),
        freeLoot: "-",
        chanceToWin: "1 NFT per Tier",
      },
      {
        each: 0.048,
        total: 0.048 * 2,
        number: 2,
        save: calcSave(0.05, 0.048, 2),
        freeLoot: "-",
        chanceToWin: "2 NFT per Tier",
      },
      {
        each: 0.045,
        total: 0.045 * 3,
        number: 3,
        save: calcSave(0.05, 0.045, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "$150 of $ETH",
      },
      {
        each: 0.043,
        total: 0.043 * 4,
        number: 4,
        save: calcSave(0.05, 0.043, 4),
        freeLoot: "Cap",
        chanceToWin: "$250 of $ETH",
      },
      {
        each: 0.04,
        total: 0.04 * 5,
        number: 5,
        save: calcSave(0.05, 0.04, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "0.5 $ETH ",
      },
      {
        each: 0.035,
        total: Number(0.035 * 10).toFixed(2),
        number: 10,
        save: calcSave(0.05, 0.035, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "$1000 of $ETH",
      },
    ],
    [
      {
        each: 0.053,
        total: 0.053,
        number: 1,
        save: calcSave(0.053, 0.053, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.1,
        number: 2,
        save: calcSave(0.053, 0.05, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.141,
        number: 3,
        save: calcSave(0.053, 0.047, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.18,
        number: 4,
        save: calcSave(0.053, 0.045, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.042,
        total: 0.21,
        number: 5,
        save: calcSave(0.053, 0.042, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.037,
        total: 0.37,
        number: 10,
        save: calcSave(0.053, 0.037, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.056,
        total: 0.056,
        number: 1,
        save: calcSave(0.056, 0.056, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.106,
        number: 2,
        save: calcSave(0.056, 0.053, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.15,
        number: 3,
        save: calcSave(0.056, 0.05, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.188,
        number: 4,
        save: calcSave(0.056, 0.047, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.225,
        number: 5,
        save: calcSave(0.056, 0.045, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.039,
        total: 0.39,
        number: 10,
        save: calcSave(0.056, 0.039, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.059,
        total: 0.059,
        number: 1,
        save: calcSave(0.059, 0.059, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.112,
        number: 2,
        save: calcSave(0.059, 0.056, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.159,
        number: 3,
        save: calcSave(0.059, 0.053, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.2,
        number: 4,
        save: calcSave(0.059, 0.05, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.235,
        number: 5,
        save: calcSave(0.059, 0.047, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.041,
        total: 0.41,
        number: 10,
        save: calcSave(0.059, 0.041, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.062,
        total: 0.062,
        number: 1,
        save: calcSave(0.062, 0.062, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.118,
        number: 2,
        save: calcSave(0.062, 0.059, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.168,
        number: 3,
        save: calcSave(0.062, 0.056, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.212,
        number: 4,
        save: calcSave(0.062, 0.053, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.25,
        number: 5,
        save: calcSave(0.062, 0.05, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.43,
        number: 10,
        save: calcSave(0.062, 0.043, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.065,
        total: 0.065,
        number: 1,
        save: calcSave(0.065, 0.065, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.124,
        number: 2,
        save: calcSave(0.065, 0.062, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.177,
        number: 3,
        save: calcSave(0.065, 0.059, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.224,
        number: 4,
        save: calcSave(0.065, 0.056, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.052,
        total: 0.26,
        number: 5,
        save: calcSave(0.065, 0.052, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.046,
        total: 0.46,
        number: 10,
        save: calcSave(0.065, 0.046, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.069,
        total: 0.069,
        number: 1,
        save: calcSave(0.069, 0.069, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.13,
        number: 2,
        save: calcSave(0.069, 0.065, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.186,
        number: 3,
        save: calcSave(0.069, 0.062, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.236,
        number: 4,
        save: calcSave(0.069, 0.059, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.055,
        total: 0.275,
        number: 5,
        save: calcSave(0.069, 0.055, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.48,
        number: 10,
        save: calcSave(0.069, 0.048, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.073,
        total: 0.073,
        number: 1,
        save: calcSave(0.073, 0.073, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.138,
        number: 2,
        save: calcSave(0.073, 0.069, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.195,
        number: 3,
        save: calcSave(0.073, 0.065, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.248,
        number: 4,
        save: calcSave(0.073, 0.062, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.058,
        total: 0.29,
        number: 5,
        save: calcSave(0.073, 0.058, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.051,
        total: 0.51,
        number: 10,
        save: calcSave(0.073, 0.051, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.077,
        total: 0.077,
        number: 1,
        save: calcSave(0.077, 0.077, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.146,
        number: 2,
        save: calcSave(0.077, 0.073, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.207,
        number: 3,
        save: calcSave(0.077, 0.069, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.26,
        number: 4,
        save: calcSave(0.077, 0.065, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.061,
        total: 0.305,
        number: 5,
        save: calcSave(0.077, 0.061, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.054,
        total: 0.54,
        number: 10,
        save: calcSave(0.077, 0.054, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.081,
        total: 0.081,
        number: 1,
        save: calcSave(0.081, 0.081, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.077,
        total: 0.154,
        number: 2,
        save: calcSave(0.081, 0.077, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.219,
        number: 3,
        save: calcSave(0.081, 0.073, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.276,
        number: 4,
        save: calcSave(0.081, 0.069, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.325,
        number: 5,
        save: calcSave(0.081, 0.065, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.057,
        total: 0.57,
        number: 10,
        save: calcSave(0.081, 0.057, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
  ],
  [
    [], //never used
    [
      {
        each: 0.05,
        total: 0.05 * 1,
        number: 1,
        save: calcSave(0.05, 0.05, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.048 * 2,
        number: 2,
        save: calcSave(0.05, 0.048, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.045 * 3,
        number: 3,
        save: calcSave(0.05, 0.045, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.043 * 4,
        number: 4,
        save: calcSave(0.05, 0.043, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.04,
        total: 0.04 * 5,
        number: 5,
        save: calcSave(0.05, 0.04, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.035,
        total: Number(0.035 * 10).toFixed(2),
        number: 10,
        save: calcSave(0.05, 0.035, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.053,
        total: 0.053,
        number: 1,
        save: calcSave(0.053, 0.053, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.1,
        number: 2,
        save: calcSave(0.053, 0.05, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.141,
        number: 3,
        save: calcSave(0.053, 0.047, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.18,
        number: 4,
        save: calcSave(0.053, 0.045, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.042,
        total: 0.21,
        number: 5,
        save: calcSave(0.053, 0.042, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.037,
        total: 0.37,
        number: 10,
        save: calcSave(0.053, 0.037, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.056,
        total: 0.056,
        number: 1,
        save: calcSave(0.056, 0.056, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.106,
        number: 2,
        save: calcSave(0.056, 0.053, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.15,
        number: 3,
        save: calcSave(0.056, 0.05, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.188,
        number: 4,
        save: calcSave(0.056, 0.047, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.225,
        number: 5,
        save: calcSave(0.056, 0.045, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.039,
        total: 0.39,
        number: 10,
        save: calcSave(0.056, 0.039, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.059,
        total: 0.059,
        number: 1,
        save: calcSave(0.059, 0.059, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.112,
        number: 2,
        save: calcSave(0.059, 0.056, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.159,
        number: 3,
        save: calcSave(0.059, 0.053, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.2,
        number: 4,
        save: calcSave(0.059, 0.05, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.235,
        number: 5,
        save: calcSave(0.059, 0.047, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.041,
        total: 0.41,
        number: 10,
        save: calcSave(0.059, 0.041, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.062,
        total: 0.062,
        number: 1,
        save: calcSave(0.062, 0.062, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.118,
        number: 2,
        save: calcSave(0.062, 0.059, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.168,
        number: 3,
        save: calcSave(0.062, 0.056, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.212,
        number: 4,
        save: calcSave(0.062, 0.053, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.25,
        number: 5,
        save: calcSave(0.062, 0.05, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.43,
        number: 10,
        save: calcSave(0.062, 0.043, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.065,
        total: 0.065,
        number: 1,
        save: calcSave(0.065, 0.065, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.124,
        number: 2,
        save: calcSave(0.065, 0.062, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.177,
        number: 3,
        save: calcSave(0.065, 0.059, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.224,
        number: 4,
        save: calcSave(0.065, 0.056, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.052,
        total: 0.26,
        number: 5,
        save: calcSave(0.065, 0.052, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.046,
        total: 0.46,
        number: 10,
        save: calcSave(0.065, 0.046, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.069,
        total: 0.069,
        number: 1,
        save: calcSave(0.069, 0.069, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.13,
        number: 2,
        save: calcSave(0.069, 0.065, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.186,
        number: 3,
        save: calcSave(0.069, 0.062, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.236,
        number: 4,
        save: calcSave(0.069, 0.059, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.055,
        total: 0.275,
        number: 5,
        save: calcSave(0.069, 0.055, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.48,
        number: 10,
        save: calcSave(0.069, 0.048, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.073,
        total: 0.073,
        number: 1,
        save: calcSave(0.073, 0.073, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.138,
        number: 2,
        save: calcSave(0.073, 0.069, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.195,
        number: 3,
        save: calcSave(0.073, 0.065, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.248,
        number: 4,
        save: calcSave(0.073, 0.062, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.058,
        total: 0.29,
        number: 5,
        save: calcSave(0.073, 0.058, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.051,
        total: 0.51,
        number: 10,
        save: calcSave(0.073, 0.051, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.077,
        total: 0.077,
        number: 1,
        save: calcSave(0.077, 0.077, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.146,
        number: 2,
        save: calcSave(0.077, 0.073, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.207,
        number: 3,
        save: calcSave(0.077, 0.069, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.26,
        number: 4,
        save: calcSave(0.077, 0.065, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.061,
        total: 0.305,
        number: 5,
        save: calcSave(0.077, 0.061, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.054,
        total: 0.54,
        number: 10,
        save: calcSave(0.077, 0.054, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.081,
        total: 0.081,
        number: 1,
        save: calcSave(0.081, 0.081, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.077,
        total: 0.154,
        number: 2,
        save: calcSave(0.081, 0.077, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.219,
        number: 3,
        save: calcSave(0.081, 0.073, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.276,
        number: 4,
        save: calcSave(0.081, 0.069, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.325,
        number: 5,
        save: calcSave(0.081, 0.065, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.057,
        total: 0.57,
        number: 10,
        save: calcSave(0.081, 0.057, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
  ],
  [
    [], //never used
    [
      {
        each: 0.05,
        total: 0.05 * 1,
        number: 1,
        save: calcSave(0.05, 0.05, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.048 * 2,
        number: 2,
        save: calcSave(0.05, 0.048, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.045 * 3,
        number: 3,
        save: calcSave(0.05, 0.045, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.043 * 4,
        number: 4,
        save: calcSave(0.05, 0.043, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.04,
        total: 0.04 * 5,
        number: 5,
        save: calcSave(0.05, 0.04, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.035,
        total: Number(0.035 * 10).toFixed(2),
        number: 10,
        save: calcSave(0.05, 0.035, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.053,
        total: 0.053,
        number: 1,
        save: calcSave(0.053, 0.053, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.1,
        number: 2,
        save: calcSave(0.053, 0.05, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.141,
        number: 3,
        save: calcSave(0.053, 0.047, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.18,
        number: 4,
        save: calcSave(0.053, 0.045, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.042,
        total: 0.21,
        number: 5,
        save: calcSave(0.053, 0.042, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.037,
        total: 0.37,
        number: 10,
        save: calcSave(0.053, 0.037, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.056,
        total: 0.056,
        number: 1,
        save: calcSave(0.056, 0.056, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.106,
        number: 2,
        save: calcSave(0.056, 0.053, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.15,
        number: 3,
        save: calcSave(0.056, 0.05, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.188,
        number: 4,
        save: calcSave(0.056, 0.047, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.225,
        number: 5,
        save: calcSave(0.056, 0.045, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.039,
        total: 0.39,
        number: 10,
        save: calcSave(0.056, 0.039, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.059,
        total: 0.059,
        number: 1,
        save: calcSave(0.059, 0.059, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.112,
        number: 2,
        save: calcSave(0.059, 0.056, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.159,
        number: 3,
        save: calcSave(0.059, 0.053, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.2,
        number: 4,
        save: calcSave(0.059, 0.05, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.235,
        number: 5,
        save: calcSave(0.059, 0.047, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.041,
        total: 0.41,
        number: 10,
        save: calcSave(0.059, 0.041, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.062,
        total: 0.062,
        number: 1,
        save: calcSave(0.062, 0.062, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.118,
        number: 2,
        save: calcSave(0.062, 0.059, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.168,
        number: 3,
        save: calcSave(0.062, 0.056, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.212,
        number: 4,
        save: calcSave(0.062, 0.053, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.25,
        number: 5,
        save: calcSave(0.062, 0.05, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.43,
        number: 10,
        save: calcSave(0.062, 0.043, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.065,
        total: 0.065,
        number: 1,
        save: calcSave(0.065, 0.065, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.124,
        number: 2,
        save: calcSave(0.065, 0.062, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.177,
        number: 3,
        save: calcSave(0.065, 0.059, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.224,
        number: 4,
        save: calcSave(0.065, 0.056, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.052,
        total: 0.26,
        number: 5,
        save: calcSave(0.065, 0.052, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.046,
        total: 0.46,
        number: 10,
        save: calcSave(0.065, 0.046, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.069,
        total: 0.069,
        number: 1,
        save: calcSave(0.069, 0.069, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.13,
        number: 2,
        save: calcSave(0.069, 0.065, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.186,
        number: 3,
        save: calcSave(0.069, 0.062, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.236,
        number: 4,
        save: calcSave(0.069, 0.059, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.055,
        total: 0.275,
        number: 5,
        save: calcSave(0.069, 0.055, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.48,
        number: 10,
        save: calcSave(0.069, 0.048, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.073,
        total: 0.073,
        number: 1,
        save: calcSave(0.073, 0.073, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.138,
        number: 2,
        save: calcSave(0.073, 0.069, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.195,
        number: 3,
        save: calcSave(0.073, 0.065, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.248,
        number: 4,
        save: calcSave(0.073, 0.062, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.058,
        total: 0.29,
        number: 5,
        save: calcSave(0.073, 0.058, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.051,
        total: 0.51,
        number: 10,
        save: calcSave(0.073, 0.051, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.077,
        total: 0.077,
        number: 1,
        save: calcSave(0.077, 0.077, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.146,
        number: 2,
        save: calcSave(0.077, 0.073, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.207,
        number: 3,
        save: calcSave(0.077, 0.069, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.26,
        number: 4,
        save: calcSave(0.077, 0.065, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.061,
        total: 0.305,
        number: 5,
        save: calcSave(0.077, 0.061, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.054,
        total: 0.54,
        number: 10,
        save: calcSave(0.077, 0.054, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.081,
        total: 0.081,
        number: 1,
        save: calcSave(0.081, 0.081, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.077,
        total: 0.154,
        number: 2,
        save: calcSave(0.081, 0.077, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.219,
        number: 3,
        save: calcSave(0.081, 0.073, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.276,
        number: 4,
        save: calcSave(0.081, 0.069, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.325,
        number: 5,
        save: calcSave(0.081, 0.065, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.057,
        total: 0.57,
        number: 10,
        save: calcSave(0.081, 0.057, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
  ],
  [
    [], //never used
    [
      {
        each: 0.05,
        total: 0.05 * 1,
        number: 1,
        save: calcSave(0.05, 0.05, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.048 * 2,
        number: 2,
        save: calcSave(0.05, 0.048, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.045 * 3,
        number: 3,
        save: calcSave(0.05, 0.045, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.043 * 4,
        number: 4,
        save: calcSave(0.05, 0.043, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.04,
        total: 0.04 * 5,
        number: 5,
        save: calcSave(0.05, 0.04, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.035,
        total: Number(0.035 * 10).toFixed(2),
        number: 10,
        save: calcSave(0.05, 0.035, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.053,
        total: 0.053,
        number: 1,
        save: calcSave(0.053, 0.053, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.1,
        number: 2,
        save: calcSave(0.053, 0.05, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.141,
        number: 3,
        save: calcSave(0.053, 0.047, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.18,
        number: 4,
        save: calcSave(0.053, 0.045, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.042,
        total: 0.21,
        number: 5,
        save: calcSave(0.053, 0.042, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.037,
        total: 0.37,
        number: 10,
        save: calcSave(0.053, 0.037, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.056,
        total: 0.056,
        number: 1,
        save: calcSave(0.056, 0.056, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.106,
        number: 2,
        save: calcSave(0.056, 0.053, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.15,
        number: 3,
        save: calcSave(0.056, 0.05, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.188,
        number: 4,
        save: calcSave(0.056, 0.047, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.225,
        number: 5,
        save: calcSave(0.056, 0.045, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.039,
        total: 0.39,
        number: 10,
        save: calcSave(0.056, 0.039, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.059,
        total: 0.059,
        number: 1,
        save: calcSave(0.059, 0.059, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.112,
        number: 2,
        save: calcSave(0.059, 0.056, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.159,
        number: 3,
        save: calcSave(0.059, 0.053, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.2,
        number: 4,
        save: calcSave(0.059, 0.05, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.235,
        number: 5,
        save: calcSave(0.059, 0.047, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.041,
        total: 0.41,
        number: 10,
        save: calcSave(0.059, 0.041, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.062,
        total: 0.062,
        number: 1,
        save: calcSave(0.062, 0.062, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.118,
        number: 2,
        save: calcSave(0.062, 0.059, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.168,
        number: 3,
        save: calcSave(0.062, 0.056, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.212,
        number: 4,
        save: calcSave(0.062, 0.053, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.25,
        number: 5,
        save: calcSave(0.062, 0.05, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.43,
        number: 10,
        save: calcSave(0.062, 0.043, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.065,
        total: 0.065,
        number: 1,
        save: calcSave(0.065, 0.065, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.124,
        number: 2,
        save: calcSave(0.065, 0.062, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.177,
        number: 3,
        save: calcSave(0.065, 0.059, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.224,
        number: 4,
        save: calcSave(0.065, 0.056, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.052,
        total: 0.26,
        number: 5,
        save: calcSave(0.065, 0.052, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.046,
        total: 0.46,
        number: 10,
        save: calcSave(0.065, 0.046, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.069,
        total: 0.069,
        number: 1,
        save: calcSave(0.069, 0.069, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.13,
        number: 2,
        save: calcSave(0.069, 0.065, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.186,
        number: 3,
        save: calcSave(0.069, 0.062, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.236,
        number: 4,
        save: calcSave(0.069, 0.059, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.055,
        total: 0.275,
        number: 5,
        save: calcSave(0.069, 0.055, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.48,
        number: 10,
        save: calcSave(0.069, 0.048, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.073,
        total: 0.073,
        number: 1,
        save: calcSave(0.073, 0.073, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.138,
        number: 2,
        save: calcSave(0.073, 0.069, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.195,
        number: 3,
        save: calcSave(0.073, 0.065, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.248,
        number: 4,
        save: calcSave(0.073, 0.062, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.058,
        total: 0.29,
        number: 5,
        save: calcSave(0.073, 0.058, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.051,
        total: 0.51,
        number: 10,
        save: calcSave(0.073, 0.051, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.077,
        total: 0.077,
        number: 1,
        save: calcSave(0.077, 0.077, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.146,
        number: 2,
        save: calcSave(0.077, 0.073, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.207,
        number: 3,
        save: calcSave(0.077, 0.069, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.26,
        number: 4,
        save: calcSave(0.077, 0.065, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.061,
        total: 0.305,
        number: 5,
        save: calcSave(0.077, 0.061, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.054,
        total: 0.54,
        number: 10,
        save: calcSave(0.077, 0.054, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.081,
        total: 0.081,
        number: 1,
        save: calcSave(0.081, 0.081, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.077,
        total: 0.154,
        number: 2,
        save: calcSave(0.081, 0.077, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.219,
        number: 3,
        save: calcSave(0.081, 0.073, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.276,
        number: 4,
        save: calcSave(0.081, 0.069, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.325,
        number: 5,
        save: calcSave(0.081, 0.065, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.057,
        total: 0.57,
        number: 10,
        save: calcSave(0.081, 0.057, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
  ],
  [
    [], //never used
    [
      {
        each: 0.05,
        total: 0.05 * 1,
        number: 1,
        save: calcSave(0.05, 0.05, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.048 * 2,
        number: 2,
        save: calcSave(0.05, 0.048, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.045 * 3,
        number: 3,
        save: calcSave(0.05, 0.045, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.043 * 4,
        number: 4,
        save: calcSave(0.05, 0.043, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.04,
        total: 0.04 * 5,
        number: 5,
        save: calcSave(0.05, 0.04, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.035,
        total: Number(0.035 * 10).toFixed(2),
        number: 10,
        save: calcSave(0.05, 0.035, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.053,
        total: 0.053,
        number: 1,
        save: calcSave(0.053, 0.053, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.1,
        number: 2,
        save: calcSave(0.053, 0.05, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.141,
        number: 3,
        save: calcSave(0.053, 0.047, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.18,
        number: 4,
        save: calcSave(0.053, 0.045, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.042,
        total: 0.21,
        number: 5,
        save: calcSave(0.053, 0.042, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.037,
        total: 0.37,
        number: 10,
        save: calcSave(0.053, 0.037, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.056,
        total: 0.056,
        number: 1,
        save: calcSave(0.056, 0.056, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.106,
        number: 2,
        save: calcSave(0.056, 0.053, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.15,
        number: 3,
        save: calcSave(0.056, 0.05, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.188,
        number: 4,
        save: calcSave(0.056, 0.047, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.045,
        total: 0.225,
        number: 5,
        save: calcSave(0.056, 0.045, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.039,
        total: 0.39,
        number: 10,
        save: calcSave(0.056, 0.039, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.059,
        total: 0.059,
        number: 1,
        save: calcSave(0.059, 0.059, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.112,
        number: 2,
        save: calcSave(0.059, 0.056, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.159,
        number: 3,
        save: calcSave(0.059, 0.053, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.2,
        number: 4,
        save: calcSave(0.059, 0.05, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.047,
        total: 0.235,
        number: 5,
        save: calcSave(0.059, 0.047, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.041,
        total: 0.41,
        number: 10,
        save: calcSave(0.059, 0.041, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.062,
        total: 0.062,
        number: 1,
        save: calcSave(0.062, 0.062, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.118,
        number: 2,
        save: calcSave(0.062, 0.059, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.168,
        number: 3,
        save: calcSave(0.062, 0.056, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.053,
        total: 0.212,
        number: 4,
        save: calcSave(0.062, 0.053, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.05,
        total: 0.25,
        number: 5,
        save: calcSave(0.062, 0.05, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.043,
        total: 0.43,
        number: 10,
        save: calcSave(0.062, 0.043, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.065,
        total: 0.065,
        number: 1,
        save: calcSave(0.065, 0.065, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.124,
        number: 2,
        save: calcSave(0.065, 0.062, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.177,
        number: 3,
        save: calcSave(0.065, 0.059, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.056,
        total: 0.224,
        number: 4,
        save: calcSave(0.065, 0.056, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.052,
        total: 0.26,
        number: 5,
        save: calcSave(0.065, 0.052, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.046,
        total: 0.46,
        number: 10,
        save: calcSave(0.065, 0.046, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.069,
        total: 0.069,
        number: 1,
        save: calcSave(0.069, 0.069, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.13,
        number: 2,
        save: calcSave(0.069, 0.065, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.186,
        number: 3,
        save: calcSave(0.069, 0.062, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.059,
        total: 0.236,
        number: 4,
        save: calcSave(0.069, 0.059, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.055,
        total: 0.275,
        number: 5,
        save: calcSave(0.069, 0.055, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.048,
        total: 0.48,
        number: 10,
        save: calcSave(0.069, 0.048, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.073,
        total: 0.073,
        number: 1,
        save: calcSave(0.073, 0.073, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.138,
        number: 2,
        save: calcSave(0.073, 0.069, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.195,
        number: 3,
        save: calcSave(0.073, 0.065, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.062,
        total: 0.248,
        number: 4,
        save: calcSave(0.073, 0.062, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.058,
        total: 0.29,
        number: 5,
        save: calcSave(0.073, 0.058, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.051,
        total: 0.51,
        number: 10,
        save: calcSave(0.073, 0.051, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.077,
        total: 0.077,
        number: 1,
        save: calcSave(0.077, 0.077, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.146,
        number: 2,
        save: calcSave(0.077, 0.073, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.207,
        number: 3,
        save: calcSave(0.077, 0.069, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.26,
        number: 4,
        save: calcSave(0.077, 0.065, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.061,
        total: 0.305,
        number: 5,
        save: calcSave(0.077, 0.061, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.054,
        total: 0.54,
        number: 10,
        save: calcSave(0.077, 0.054, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
    [
      {
        each: 0.081,
        total: 0.081,
        number: 1,
        save: calcSave(0.081, 0.081, 1),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.077,
        total: 0.154,
        number: 2,
        save: calcSave(0.081, 0.077, 2),
        freeLoot: "-",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.073,
        total: 0.219,
        number: 3,
        save: calcSave(0.081, 0.073, 3),
        freeLoot: "Sticker Pack",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.069,
        total: 0.276,
        number: 4,
        save: calcSave(0.081, 0.069, 4),
        freeLoot: "Cap",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.065,
        total: 0.325,
        number: 5,
        save: calcSave(0.081, 0.065, 5),
        freeLoot: "Tee/Cap/Mouse Pad",
        chanceToWin: "2 ETH",
      },
      {
        each: 0.057,
        total: 0.57,
        number: 10,
        save: calcSave(0.081, 0.057, 10),
        freeLoot: "Hoodie/Tee & Cap",
        chanceToWin: "2 ETH",
      },
    ],
  ],
];
